# -*- coding: utf-8 -*-
"""lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXhebm5KqsIYayMFL69KwhQRd0ukB4_e
"""

#creating the list
l=[x for x in range(2,300,2)] 
# print squared items
for item in l :
  if item==1 :
   print ("the length of the list is ",len(l)) 
  print (item ," squared is ", item**2)

#check if 57 is in the list in one line 
if (57 in l) : print ("Yes , 57 is in the list") 
else : print (" No , 57 is not in the list")